//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineshop1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Registertbl
    {
        [Required(ErrorMessage = "please enter username")]
        [MinLength(5, ErrorMessage = "Min length should be 5")]
        public string uname { get; set; }

        [Required(ErrorMessage = "please enter password")]
        [MinLength(5, ErrorMessage = "Min length should be 5")]
        public string password { get; set; }

        [Range(15, 60, ErrorMessage = "Invalid age to register")]
        public Nullable<int> age { get; set; }

        [Required(ErrorMessage = "please enter valid email")]
        [EmailAddress(ErrorMessage = "invalid email")]
        public string email { get; set; }
        public string nationality { get; set; }
    }
}
